import { describe, expect, it } from 'vitest';
import { analyzeJsDeps } from './index';
import { pkgFromKey, parsePnpmLock } from './pnpm-lock';
import { parseYarnLock } from './yarn-lock';

const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz#abc"
  integrity sha512-AAAA

"@scope/evil@^2.0.0", "@scope/evil@^2.1.0":
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/@scope/evil/-/evil-2.1.0.tgz#def"
  integrity sha512-BBBB
  dependencies:
    left-pad "^1.3.0"
`;

const YARN_BERRY = `__metadata:
  version: 6
  cacheKey: 8

"left-pad@npm:^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
  languageName: node
  linkType: hard
`;

describe('parseYarnLock', () => {
  it('parses v1 classic entries, including a scoped multi-descriptor block', () => {
    const deps = parseYarnLock(YARN_V1);
    expect(deps.get('left-pad')).toBe('1.3.0');
    expect(deps.get('@scope/evil')).toBe('2.1.0');
    expect(deps.size).toBe(2); // the `dependencies:` sub-block is not a resolved package
  });

  it('parses common Berry (v2+) form and ignores __metadata', () => {
    const deps = parseYarnLock(YARN_BERRY);
    expect(deps.get('left-pad')).toBe('1.3.0');
    expect(deps.has('__metadata')).toBe(false);
    expect(deps.size).toBe(1);
  });
});

describe('pkgFromKey (pnpm packages: keys across versions)', () => {
  it('normalizes v9, v6 and v5 key forms, stripping peer suffixes', () => {
    expect(pkgFromKey('left-pad@1.3.0')).toEqual({ pkg: 'left-pad', version: '1.3.0' }); // v9
    expect(pkgFromKey('/@babel/core@7.20.0')).toEqual({ pkg: '@babel/core', version: '7.20.0' }); // v6
    expect(pkgFromKey('/@babel/core@7.20.0(react@18.0.0)')).toEqual({
      pkg: '@babel/core',
      version: '7.20.0',
    }); // v6 + peer
    expect(pkgFromKey('/left-pad/1.3.0')).toEqual({ pkg: 'left-pad', version: '1.3.0' }); // v5
    expect(pkgFromKey('/foo/1.0.0_bar@2.0.0')).toEqual({ pkg: 'foo', version: '1.0.0' }); // v5 + peer
  });

  it('skips non-registry / version-less keys', () => {
    expect(pkgFromKey('foo@github:owner/repo')).toBeNull();
  });
});

const PNPM_V6 = `lockfileVersion: '6.0'

packages:

  /left-pad@1.3.0:
    resolution: {integrity: sha512-AAAA}
    dev: false

  /evil-pkg@2.0.0:
    resolution: {integrity: sha512-BBBB}
    dev: false
`;

describe('parsePnpmLock', () => {
  it('parses the packages map into resolved name → version', () => {
    const deps = parsePnpmLock(PNPM_V6);
    expect(deps.get('left-pad')).toBe('1.3.0');
    expect(deps.get('evil-pkg')).toBe('2.0.0');
  });
});

describe('analyzeJsDeps', () => {
  const base = `# yarn lockfile v1

left-pad@^1.3.0:
  version "1.3.0"
`;
  const head = `# yarn lockfile v1

left-pad@^1.3.0:
  version "1.3.0"

evil-pkg@^2.0.0:
  version "2.0.0"
`;

  it('emits a new-dependency entry + install-capable dep node with a controls edge on an added dep', () => {
    const result = analyzeJsDeps({ format: 'yarn', headLockfile: head, baseLockfile: base });
    const dep = result.nodes.find((n) => n.kind === 'dependency' && n.pkg === 'evil-pkg');
    expect(dep).toBeDefined();
    expect(dep && 'hasInstallScript' in dep && dep.hasInstallScript).toBe(true);
    expect(dep && 'ecosystem' in dep && dep.ecosystem).toBe('npm');
    expect(result.nodes.some((n) => n.kind === 'entry' && n.entryKind === 'new-dependency')).toBe(
      true,
    );
    expect(result.edges.some((e) => e.edge.kind === 'controls')).toBe(true);
    // left-pad is unchanged → not flagged.
    expect(result.nodes.some((n) => n.kind === 'dependency' && n.pkg === 'left-pad')).toBe(false);
  });

  it('flags a version bump as a changed dependency', () => {
    const bumped = `# yarn lockfile v1

left-pad@^1.3.0:
  version "2.0.0"
`;
    const result = analyzeJsDeps({ format: 'yarn', headLockfile: bumped, baseLockfile: base });
    const entry = result.nodes.find((n) => n.kind === 'entry');
    expect(entry && 'label' in entry && entry.label).toContain('changed');
  });

  it('emits nothing in whole-repo mode (no base ref) — an existing lockfile is trusted', () => {
    const result = analyzeJsDeps({ format: 'yarn', headLockfile: head });
    expect(result.nodes).toEqual([]);
    expect(result.diagnostics).toEqual([]);
  });

  it('fails closed with an error diagnostic on an unparseable pnpm lockfile', () => {
    const result = analyzeJsDeps({
      format: 'pnpm',
      headLockfile: ':\n  - [unbalanced',
      baseLockfile: '',
    });
    expect(result.diagnostics.some((d) => d.level === 'error')).toBe(true);
  });
});
