#!/usr/bin/env bash
# Regenerate src/analyzers/ci/agent-release-shas.ts (ticket 0065): every release tag of each
# profiled agent action, keyed by the commit SHA a workflow pins in `uses: owner/repo@<sha>`.
# agentProfileFor resolves a pinned SHA to its tag, then applies the profile's version range.
#
# A commit carrying several tags (a moving `v1` and `v1.0.238`) keeps the most specific one.
#
# Usage: scripts/refresh-agent-shas.sh   (needs `gh` authenticated; read-only GitHub API)
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/src/analyzers/ci/agent-release-shas.ts"
ACTIONS=(
  anthropics/claude-code-action
  openai/codex-action
  google-github-actions/run-gemini-cli
  actions/ai-inference
)

{
  echo '// GENERATED by scripts/refresh-agent-shas.sh — do not edit by hand.'
  echo '// Release tags of each profiled agent action, keyed by the commit SHA a workflow pins.'
  echo "// Refreshed $(date -u +%Y-%m-%d)."
  echo 'export const AGENT_RELEASE_SHAS: Record<string, Record<string, string>> = {'
  for repo in "${ACTIONS[@]}"; do
    echo "  '$repo': {"
    gh api --paginate "repos/$repo/tags?per_page=100" --jq '.[] | "\(.commit.sha)\t\(.name)"' \
      | grep -E $'\tv?[0-9]+(\\.[0-9]+){0,2}$' \
      | awk -F'\t' '{ n = gsub(/\./, ".", $2); if (!($1 in best) || n > dots[$1]) { best[$1] = $2; dots[$1] = n } }
          END { for (sha in best) printf "    \x27%s\x27: \x27%s\x27,\n", sha, best[sha] }' \
      | sort
    echo '  },'
  done
  echo '};'
} >"$OUT.tmp"
mv "$OUT.tmp" "$OUT"
(cd "$ROOT" && npx prettier --write "$OUT" >/dev/null)
echo "wrote $OUT ($(grep -cE "^\s+'?[0-9a-f]{40}'?:" "$OUT") SHAs)"
